### PR TITLE
drop python<=3.7 support

### PR DESCRIPTION
**Pull request by kloczek**
https://endoflife.date/python
Python 3.7 has been EOSed 27 Jun 2023.
Filter all code over `pyupgrade --py38`.

### CODE REVIEW

**Comment by abersheeran** [comment]
Thanks for the PR, but a2wsgi currently has no plans to deprecate support for 3.7. There are still a large number of users stuck on this version.

a2wsgi expects to support 3.7 until the test component fails to run simultaneously on the latest version of Python and 3.7.

**Comment by kloczek** [comment]
Accepting such PR do not need to stop supporting exact version.
It will drop such support on master.

You can simple create branch to release any updates for python <=3.7 and have master 100% clan/up-to-date.

Nevertheless I don't think that anyone will ever come with some issues on <=3.7.
As more and more modules moves to at least 3.8, some to +39 and there are already few which requires +3.10 .
For example it is not possible to build Linux based desktop without +3.10 because mesa requires rust which requires some python tools which are written only for python +3.10 and few gnome build procedures uses in meson some python +3.10 features) .All that caused that abilities to test anything new with 3.7 more than year ago dramatically shank.

**Comment by abersheeran** [comment]
Multiple branches will bring greater burden. a2wsgi is a simple and stable library, and I do not want nor have the energy to engage in complex version management. We aim to support as many versions as possible on one branch until the old version is completely incompatible with the latest version. This is a2wsgi's maintenance strategy.

**Comment by kloczek** [comment]
> Multiple branches will bring greater burden. a2wsgi is a simple and stable library,

Trust me branches are really to make that easier.
It is easier to create v-0.10.x branch and inform "**version 1.10.5 .z is last version which supports python <=3.7. If it  is anything which should be committed to that line pleas let me know about exact hashes from master ot pleas submit PR ageist v0.10.x branch**" instead support all possible version in single source tree.
I'm really sure that it would be not yo much traffic in such branch.

**Comment by abersheeran** [comment]
I know what to do, and I'm sure it will bring more maintenance costs. For example, CI does not support multiple branches now.

You are welcome to propose PR to fix BUG or improve performance.

**Comment by kloczek** [comment]
> I know what to do, and I'm sure it will bring more maintenance costs. For example, CI does not support multiple branches now.

OK so that may be only cost of such change to change CI procedure to handle branches.

**Pull request closed without merging**
